name: hire_harmony
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  dot_navigation_bar: ^1.0.2
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  fluid_bottom_nav_bar: ^1.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  gradient_icon: ^2.0.9
  persistent_bottom_nav_bar_v2: ^5.3.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
